---
name: build
on: push
jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: go.sum
      - name: Configure Go environment
        env:
          GOPROXY: "https://proxy.golang.org,direct"
          GOSUMDB: "sum.golang.org"
        run: go mod tidy
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
      - name: Display version
        run: go version
